name: Server Auto Extend

on:
  schedule:
    # 每天 UTC 时间 00:00 运行一次 (例如，北京时间早上 8 点)
    # 你可以根据需要调整这个时间
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发 workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install Playwright
      run: |
        pip install playwright
        playwright install chromium # 安装 Chromium 浏览器

    - name: Run Python script
      env:
        # 确保在 GitHub Secrets 中设置这些变量
        REMEMBER_WEB_COOKIE: ${{ secrets.REMEMBER_WEB_COOKIE }}
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        # 多服务器配置 - 选择其中一种方式设置
        SERVER_URLS: ${{ secrets.SERVER_URLS }}
        SERVER_LIST: ${{ secrets.SERVER_LIST }}
      run: python main.py
